### ISSUE TITLE
關於 VIP 的申請

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#27]
玩家 a89928795 提出詢問 VIP 要怎麼申請，目前沒有明確規定，所以藉這機會將這議題丟出來討論。

目前 VIP 擁有權限爲：

```yaml
groups:
  VIP:
    permissions:
    - dynmap.marker.*
    - worldedit.*
    - admincmd.player.gamemode
    - minecraft.command.tp
```

有 VIP 權限的人員為：（照字母順序排列）
- assassin
- BlacKaras
- danny8376
- floatj
- Mushroom_Tim
- Nfeather
- paul
- riesz
- Ureezu

詳細可參見[設定檔(OP Only)](https://git.catcafe.tw/MinecraftSnowServer/Server/blob/master/plugins/PermissionsEx/permissions.yml#L187)

**Comment by fntsrlike** [comment]
先發表個人結論，我不贊同增加 a89928795 為 VIP。

### 1. VIP 權限概要

VIP 的權限主要有：

- WorldEdit 權限
- 改變自身遊戲模式（生存、創造、冒險）的權限
- `tp` 權限
- 動態地圖關於標記的所有權限

### 2. WorldEdit 的危險性與信用基礎

其中 WorldEdit 的權限是有其危險性的，我不贊同輕易開放玩家成為 VIP。從 VIP 清單上可以看到目前 VIP 的人員九位有七位在現實中就認識的朋友，這也是因為認識的朋友比較有信任感，相信他們不會濫用權力，另外也能因為現實認識，有情誼壓力，所以具有約束力。

另外兩位特例是 assassin 和 BlacKaras。這兩位成為 VIP 前，都已經在雪服深耕很長一段時間，且的確有建造大型創作的能力與需求，而 BlacKaras 更是為 Gamma 世界建立了許多值得學習的自動化裝置與公共建設，算是信用程度良好的玩家。

所以我認為成為 VIP 有一個很重要的先前條件就是信用度，如果不是現實中有認識，就是必須有在遊戲中長期積累並作出貢獻的玩家。

### 3. 創造模式的需求與配套

當初會建立 VIP 有一個主要原因就是 Alpha 世界的性質，為了讓玩家可以直接開創造模式在 Alpha 進行創作。但目前這個需求已經可以透過 Alpha 目前的政策解套。

Alpha 的創作區已經被劃分成一個個約 500x500 大小的領地，然後每個領地都有用 WorldGuard 的 Region 進行比較細節的設置，其中也有開放領主針對自己的領地設置 33 項旗幟（flags）的權限，詳見[設定檔（OP Only）](https://git.catcafe.tw/MinecraftSnowServer/Server/blob/master/plugins/PermissionsEx/permissions.yml#L65)。

目前的想法是讓玩家領主進入領地後，直接轉為創造模式，相關議題可參見 #25，其中 @david50407 有在 https://github.com/MinecraftSnowServer/Report/issues/25#issuecomment-312024753 提到可能會有切換其他模式的需求。所以之後可能在此預設行為基礎下，另外開放玩家可自行設置該領地遊戲模式的旗幟。

有政策和這個配套措施後，基本上創造模式就不太會是想成為 VIP 玩家的主要誘因了。

另外 Gamma 基本上是屬於生存地圖，鼓勵玩家以生存模式進行創作，不希望有人透過創造模式影響整體玩家的遊戲樂趣與熱情（想想當你辛辛苦苦採礦、掛機、冒險才收集到這些建材，結果有玩家直接創造模式的反差感），所以想在 Gamma 用創造模式建設的需求也不成立。

### 4. 其他權限
至於 `tp` 指令權限，在有 `tpa` 和 `home` 兩大傳送指令的情況下，倒也不是必要性的。而動態地圖的主要標記功能早就對一般玩家開放（如下），就更不需要討論了。

```yaml
groups:
  Builder:
    permissions:
    - dynmap.marker.list
    - dynmap.marker.delete
    - dynmap.marker.add
    - dynmap.marker.movehere
    - dynmap.marker.update
```

### 5. 結論
基於以上幾點，目前針對 VIP 權限是否開放申請，我是覺得沒有特別必要，也不太需要設立條件。通常就是有 OP 覺得某玩家有達到可信任程度，且覺得他可能需要 WE 進行創作，就會詢問其他 OP 意見，若 OP 群皆同意，就會提升玩家為 VIP。我認為這種方式倒也不需要改變。

最後，a89928795 所提到想成為 VIP 的原因在於「想用創造模式蓋東西」（參見下方對話紀錄摘要），亦可在「3. 創造模式的需求與配套」達到目的。至於有閒時間就幫助人，這件事倒與是否為 VIP 沒有特別關係，一般玩家之間本來就可以互相幫助了。所以這也是我為什麼不贊成的原因。

當然，若單純是想要頭銜，就又是另一個話題了，在這邊先不加以討論。


#### *對話紀錄摘要*

```
sntc06 [11:40 PM] 
有什麼特別想申請VIP的原因嗎？ e.g. 想用創造模式蓋東西

a89928795 APP [11:41 PM] 
原因:享用創造愛東西 有閒時間 就幫助人^^
```
